// https://www.akc.org/

export default [
    {
        id: 0,
        breed: 'German Shepherd',
        popularity: "Ranks 2 of 195",
        Height: '24-26 inches (male), 22-24 inches (female)',
        Weight: '65-90 pounds (male), 50-70 pounds (female)',
        life_expectancy: '7-10 years',
        about: 'There are many reasons why German Shepherds stand in the front rank of canine royalty, but experts say their defining attribute is character: loyalty, courage, confidence, the ability to learn commands for many tasks, and the willingness to put their life on the line in defense of loved ones. German Shepherds will be gentle family pets and steadfast guardians, but, the breed standard says, there’s a certain aloofness that does not lend itself to immediate and indiscriminate friendships.',
        grooming: 'The German Shepherd Dog has a medium-length, double coat consisting of a dense, harsh, and close-lying outer coat with a softer undercoat. The breed is easy to maintain, usually requiring just a quick brushing every few days or so to help remove loose hairs, but they do shed more profusely once or twice a year. During these periods, more frequent brushing will help control the amount of hair that ends up around the house and on the furniture. The German Shepherd only needs an occasional bath. It is important to trim or grind his nails every month if they are not worn down naturally, as overly long nails can cause pain and structural issues.',
        exercise: 'As a very active and athletic breed, the German Shepherd requires lots of exercise for his physical and mental well-being. A dog who is not exercised enough will become frustrated and likely to develop undesirable behaviors. With a puppy, you can start with short daily walks, as well as play sessions in a safely fenced area. Remember to not let the dog off leash, as even the best-trained dog can become distracted and not follow every command. Participating in canine activities such as agility, herding, tracking, and dock diving provides excellent physical and mental exercise and is fun and rewarding for both dog and owner.',
        traning: 'Early socialization and puppy training classes are vital, and continuing obedience training will help ensure that the pup will grow to be an adaptable and well-mannered adult. The German Shepherd is a highly intelligent companion and an extraordinary worker. Consistency and positive, reward-based training will yield excellent results. He is extremely bonded to his people, so he is happiest when he lives with his family. He should be raised in the household and exposed to the family’s activities. The German Shepherd Dog Club of America provides detailed training advice for owners on the club’s website.'
    },
    {
        id: 1,
        breed: 'Rottweiler',
        popularity: "Ranks 8 of 195",
        Height: '24-27 inches (male), 22-25 inches (female)',
        Weight: '93-135 pounds (male), 80-100 pounds (female)',
        life_expectancy: '9-10 years',
        about: 'A well-bred and properly raised Rottie will be calm and confident, courageous but not unduly aggressive. The aloof demeanor these world-class guardians present to outsiders belies the playfulness, and downright silliness, that endear Rotties to their loved ones. (No one told the Rottie he’s not a toy breed, so he is liable plop onto your lap for a cuddle.) Early training and socialization will harness a Rottie’s territorial instincts in a positive way.',
        grooming: 'The Rottweiler has a straight, coarse, medium-length outer coat that lies flat. The undercoat is present on the neck and thighs. He should be brushed weekly and bathed regularly. He sheds only very moderately for most of the year, although he will shed more profusely twice a year, usually in the spring and fall. His teeth should be brushed and nails trimmed weekly. The use of a grinding tool such as a Dremel is especially effective in trimming the nails.',
        exercise: 'Rottweilers love swimming, walking, and trotting, especially with their people. The breed is muscular and athletic, and should have the opportunity to exercise on a daily basis. If there are jobs to do, Rottweilers learn easily to cart and are excellent workers in herding, tracking, and obedience. There is no limit to the canine activities that the Rottweiler can learn to do. Excess weight is not good for any dog, and exercise can help to keep your Rottweiler fit and healthy.',
        traning: 'The Rottweiler must be trained starting early in his life. Leadership, puppy socialization, basic training classes, and living in the owner’s home are key to raising a well-mannered Rottweiler. Rottweilers are “people dogs” who do not do well isolated from humans and life experiences. No matter the breed, dogs must live in this world complete with strange animals and people. One expert in the breed notes, “As a Rottweiler owner, it is my responsibility to spend time, energy, and money giving my dog the opportunities to learn on a day-to-day basis.” The breed is intelligent, highly trainable and wants to please, although some may be stubborn. It is very important that discipline be consistent, fair, and firm, without being rough. Roughhousing with the Rottweiler may encourage aggression and should be avoided. Rottweilers excel in many canine sports, and the breed works with a human partner in many functional roles.'
    }
]