// https://www.akc.org/

export default [
    {
        id: 0,
        breed: 'German Shepherd',
        image: 'https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/12213218/German-Shepherd-on-White-00.jpg',
        popularity: "Ranks 2 of 195",
        Height: '24-26 inches (male), 22-24 inches (female)',
        Weight: '65-90 pounds (male), 50-70 pounds (female)',
        life_expectancy: '7-10 years',
        about: 'There are many reasons why German Shepherds stand in the front rank of canine royalty, but experts say their defining attribute is character: loyalty, courage, confidence, the ability to learn commands for many tasks, and the willingness to put their life on the line in defense of loved ones. German Shepherds will be gentle family pets and steadfast guardians, but, the breed standard says, there’s a certain aloofness that does not lend itself to immediate and indiscriminate friendships.',
        grooming: 'The German Shepherd Dog has a medium-length, double coat consisting of a dense, harsh, and close-lying outer coat with a softer undercoat. The breed is easy to maintain, usually requiring just a quick brushing every few days or so to help remove loose hairs, but they do shed more profusely once or twice a year. During these periods, more frequent brushing will help control the amount of hair that ends up around the house and on the furniture. The German Shepherd only needs an occasional bath. It is important to trim or grind his nails every month if they are not worn down naturally, as overly long nails can cause pain and structural issues.',
        exercise: 'As a very active and athletic breed, the German Shepherd requires lots of exercise for his physical and mental well-being. A dog who is not exercised enough will become frustrated and likely to develop undesirable behaviors. With a puppy, you can start with short daily walks, as well as play sessions in a safely fenced area. Remember to not let the dog off leash, as even the best-trained dog can become distracted and not follow every command. Participating in canine activities such as agility, herding, tracking, and dock diving provides excellent physical and mental exercise and is fun and rewarding for both dog and owner.',
        training: 'Early socialization and puppy training classes are vital, and continuing obedience training will help ensure that the pup will grow to be an adaptable and well-mannered adult. The German Shepherd is a highly intelligent companion and an extraordinary worker. Consistency and positive, reward-based training will yield excellent results. He is extremely bonded to his people, so he is happiest when he lives with his family. He should be raised in the household and exposed to the family’s activities. The German Shepherd Dog Club of America provides detailed training advice for owners on the club’s website.'
    },
    {
        id: 1,
        breed: 'Rottweiler',
        image: 'https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/12225004/Rottweiler-On-White-03.jpg',
        popularity: "Ranks 8 of 195",
        Height: '24-27 inches (male), 22-25 inches (female)',
        Weight: '93-135 pounds (male), 80-100 pounds (female)',
        life_expectancy: '9-10 years',
        about: 'A well-bred and properly raised Rottie will be calm and confident, courageous but not unduly aggressive. The aloof demeanor these world-class guardians present to outsiders belies the playfulness, and downright silliness, that endear Rotties to their loved ones. (No one told the Rottie he’s not a toy breed, so he is liable plop onto your lap for a cuddle.) Early training and socialization will harness a Rottie’s territorial instincts in a positive way.',
        grooming: 'The Rottweiler has a straight, coarse, medium-length outer coat that lies flat. The undercoat is present on the neck and thighs. He should be brushed weekly and bathed regularly. He sheds only very moderately for most of the year, although he will shed more profusely twice a year, usually in the spring and fall. His teeth should be brushed and nails trimmed weekly. The use of a grinding tool such as a Dremel is especially effective in trimming the nails.',
        exercise: 'Rottweilers love swimming, walking, and trotting, especially with their people. The breed is muscular and athletic, and should have the opportunity to exercise on a daily basis. If there are jobs to do, Rottweilers learn easily to cart and are excellent workers in herding, tracking, and obedience. There is no limit to the canine activities that the Rottweiler can learn to do. Excess weight is not good for any dog, and exercise can help to keep your Rottweiler fit and healthy.',
        training: 'The Rottweiler must be trained starting early in his life. Leadership, puppy socialization, basic training classes, and living in the owner’s home are key to raising a well-mannered Rottweiler. Rottweilers are “people dogs” who do not do well isolated from humans and life experiences. No matter the breed, dogs must live in this world complete with strange animals and people. One expert in the breed notes, “As a Rottweiler owner, it is my responsibility to spend time, energy, and money giving my dog the opportunities to learn on a day-to-day basis.” The breed is intelligent, highly trainable and wants to please, although some may be stubborn. It is very important that discipline be consistent, fair, and firm, without being rough. Roughhousing with the Rottweiler may encourage aggression and should be avoided. Rottweilers excel in many canine sports, and the breed works with a human partner in many functional roles.'
    },
    {
        id: 2,
        breed: ' Czechoslovakian Vlcak',
        image: 'https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/09132858/Czechoslovakian-Puppy.jpg',
        popularity: "Ranks ? of 195",
        Height: '23 - 25 inches',
        Weight: '44 - 57 pounds',
        life_expectancy: '10 - 15 years',
        about: 'The Czechoslovakian Vlcak (CSV) was originally bred for working border patrol in Czechoslovakia in the 1950s. They are currently used in Europe and the United States for search and rescue, tracking, obedience, agility, drafting, herding, and working dog sports. The CSV is bred for versatility and hardiness in harsh elements and is much more independent in nature than many other working breeds. They are an excellent choice for tracking or trailing sport/work, or as a companion for active owners who enjoy spending time doing outdoor activities such as biking, running, or hiking. They are not, however, recommended for first time owners',
        grooming: 'Czechoslovakian Vlcaks have a weather resistant coat; it naturally cleans itself of mud and dirt. They seldom need a bath and have little to no body odor. They shed twice-a-year and at that time daily brushing is required. The winter coat is thicker, heavier and longer than the shorter, thinner summer coat and this may require more grooming during the colder months of the year. Their strong, fast-growing nails should be trimmed regularly with a nail clipper or grinder to avoid overgrowth, splitting and cracking. Their ears should be checked regularly to avoid a buildup of wax and debris which can result in an infection. Teeth should be brushed regularly.',
        exercise: 'This breed is known for having boundless energy, especially during puppyhood and young adolescence. Daily long walks/runs combined with mental stimulation work well. Turning them out into the back yard by themselves does not work. A Vlcak does best when they have a “meaningful” job they can devote themselves to. They like to have an interactive experience with their owners. Activities like swimming, hiking, retrieving balls or flying discs can provide a good outlet for expending energy. A CSV may have prey drive towards small animals, so fenced enclosures and/or on-leash are always a good idea.',
        training: 'The Czechoslovakian Vlcak is a primitive breed of dog with a dominant and independent personality and so requires a different approach to training. Consistency and patience is a must. The CSV is confident, lively, active, high stamina, high energy, tough and obedient with quick reactions. They are also highly intelligent, versatile and curious. Early socialization and training is very important. With proper training, Vlcaks can excel in many different types of activities, but they need to see a purpose for the desired task. They bore very easily, do not like to do repetitive tasks and often refuse to perform the tasks regardless of treat incentives. Positive reinforcement training methods are highly recommended. The Czechoslovakian Vlcak is not recommended for first time owners as they need strong pack leadership and structure.'
    },
    {
        id: 3,
        breed: 'Doberman Pinscher',
        image: 'https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/12233854/Doberman-Pinscher-On-White-03.jpg',
        popularity: "Ranks 17 of 195",
        Height: '26 - 28 inches (male), 24 - 26 inches (female)',
        Weight: '75 - 100 pounds (male), 60 - 90 pounds (female)',
        life_expectancy: '10 - 12 years',
        about: 'Dobermans are compactly built dogs—muscular, fast, and powerful—standing between 24 to 28 inches at the shoulder. The body is sleek but substantial, and is covered with a glistening coat of black, blue, red, or fawn, with rust markings. These elegant qualities, combined with a noble wedge-shaped head and an easy, athletic way of moving, have earned Dobermans a reputation as royalty in the canine kingdom. A well-conditioned Doberman on patrol will deter all but the most foolish intruder.',
        grooming: 'Although mostly a “wash and wear” breed, some routine grooming will help to keep the Doberman in optimal condition. A quick going-over daily with a short-bristled brush or a grooming mitt will keep his coat shiny and healthy. He does not need to be bathed often. He should have his nails trimmed at least monthly, and his teeth brushed regularly. The ears should be wiped out carefully every few days—a little baby oil on a paper towel is good for this. Your veterinarian can show you how to clean your dog’s ears to avoid damage and stay on top of potential issues.',
        exercise: 'The Doberman is an energetic athlete who needs a lot of exercise and free play. A Doberman will enjoy going for long daily walks or hikes with his owner, and having a large fenced area where he can run is vital for his physical and mental well-being. Participation in canine sports such as obedience, tracking, and agility will provide exercise for mind and body and fun times together for dog and owner.',
        training: 'Dobermans are very intelligent, learn easily, respond quickly, and make loving and fun companions. However, they are very strong dogs and can become pushy, destructive, and unmanageable if not raised properly. Socialization starting in puppyhood is imperative, as is obedience training. Puppy training classes are highly recommended as well. It is every Doberman owner’s responsibility to ensure that the dog is raised to be a happy, well-mannered companion and canine citizen. The Doberman should always live inside the home with his people, rather than outdoors.'
    },
]